{{- if .Values.sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: greymatter-sync-config
  namespace: {{ .Release.Namespace }}
data:
  # property-like keys; each key maps to a simple value
  GREYMATTER_GIT_REMOTE: "{{.Values.sync.git.repo}}"
{{- end }}