{{- if .Values.sync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: greymatter-sync-secret
  namespace: plus
type: Opaque
data:
  ssh-private-key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEdFVIQlg1WmQ5RjYwWXpFTmsvNS82ZHJOKzBXRVA5RHkyb3ZkRTlINDZ5Z0FBQUtCSEV1VCtSeExrCi9nQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRHRVSEJYNVpkOUY2MFl6RU5rLzUvNmRyTiswV0VQOUR5Mm92ZEU5SDQ2eWcKQUFBRUNlYkFaNVVyaXE3ejJkZ3lhMzQvbUhCelVxbm5WRlArTkhUUitYdHZFTk5lMVFjRmZsbDMwWHJSak1RMlQvbi9wMgpzMzdSWVEvMFBMYWk5MFQwZmpyS0FBQUFIR3Q1YkdVdVoyRnNiR0ZuYUdWeVFHZHlaWGx0WVhSMFpYSXVhVzhCCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
{{- end }}