{{- if .Values.sync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: greymatter-sync-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ssh-private-key: {{ .Values.sync.git.ssh_private_key}}
{{- end }}