{{- if .Values.sync.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: greymatter-sync
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: greymatter-sync
  serviceName: "greymatter-sync"
  replicas: 1
  template:
    metadata:
      labels:
        app: greymatter-sync
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: gm-docker-secret
      volumes:
      - name: ssh-private-key
        secret:
          secretName: greymatter-sync-secret
      containers:
      - name: greymatter-sync
        image: {{ .Values.sync.image }}
        imagePullPolicy: Always
        command: ["/usr/local/bin/greymatter"]
        args: 
          - "-c"
          - "/etc/greymatter/config.toml"
          - "--api"
          - "http://{{ .Values.greymatter.xds_host }}:5555"
          - "--catalog"
          - "http://{{ .Values.greymatter.catalog_host}}:8080"
          - "sync"
          - "--ssh-private-key"
          - "/var/lib/greymatter/.ssh/ssh-private-key"
          - "--git"
          - "--forever"
          - "--branch"
          - "{{.Values.sync.git.branch}}"
          - "--interval"
          - "10s"
          - "--git-dir"
          - "/var/lib/greymatter/checkout"
          - "-e"
          - "configs"
        volumeMounts:
        - name: ssh-private-key
          readOnly: true
          mountPath: "/var/lib/greymatter/.ssh"
        env:
        - name: SSH_KNOWN_HOSTS
          value: "/tmp/known_hosts"
        - name: GREYMATTER_GIT_REMOTE
          valueFrom:
            configMapKeyRef:
              name: greymatter-sync-config
              key: GREYMATTER_GIT_REMOTE
{{- end }}