{{- if .Values.banana.enabled }}
apiVersion: v1
data:
  index.html: This is totally bananas. [xds_cluster={{ tpl .Values.banana.xds_cluster .}}]
kind: ConfigMap
metadata:
  name: banana-web
  namespace: {{ .Release.Namespace }}
{{- end }}