greymatter:
  xds_host: controlensemble.greymatter.svc.cluster.local
  catalog_host: catalog.greymatter.svc.cluster.local
  redis_host: redis.greymatter.svc

apple:
  enabled: true
  name: apple
  xds_cluster: "{{.Release.Namespace }}-apple"

banana:
  enabled: false
  name: banana
  xds_cluster: "{{.Release.Namespace }}-banana"

lettuce:
  enabled: false
  name: lettuce
  xds_cluster: "{{.Release.Namespace }}-lettuce"

tomato:
  enabled: false
  name: tomato
  xds_cluster: "{{.Release.Namespace }}-tomato"

sync:
  enabled: false
  image: quay.io/greymatterio/cli:4.3.0
  git:
    repo: git@github.com:your-org/gitops-plus.git
    branch: main
    ssh_private_key: REPLACE_THIS_BASE64