{{- if .Values.tomato.enabled }}
apiVersion: v1
data:
  index.html: You say Tomato, I say Tomato. [xds_cluster={{ tpl .Values.tomato.xds_cluster .}}]
kind: ConfigMap
metadata:
  name: tomato-web
  namespace: {{ .Release.Namespace }}
{{- end }}