{{- if .Values.apple.enabled }}
apiVersion: v1
data:
  index.html: An apple a day keeps the dentist away. [xds_cluster={{ tpl .Values.apple.xds_cluster .}}]
kind: ConfigMap
metadata:
  name: apple-web
  namespace: {{ .Release.Namespace }}
{{- end }}