metadata:
  name: gm-operator-gm-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: greymatter-operator
    namespace: gm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gm-operator-gm-operator-role
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
---

metadata:
  name: gm-operator-vector-agent-clusterrolebinding
  namespace: greymatter
subjects:
  - kind: ServiceAccount
    name: vector-agent
    namespace: greymatter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gm-operator-vector-agent
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1