
metadata:
  name: overrides-cue
  namespace: gm-operator
data:
  overrides.cue: |-
    package greymatter

    config: {
      spire: false
      openshift: false
      generate_webhook_certs: true
      enable_historical_metrics: true
      auto_copy_image_pull_secret: true
    }
kind: ConfigMap
apiVersion: v1