metadata:
  name: overrides-cue
  namespace: gm-operator
data:
  overrides.cue: |-
    package greymatter

    config: {
      spire: false
      auto_apply_mesh: true
      openshift: false
      generate_webhook_certs: true
      auto_copy_image_pull_secret: true 
    }
kind: ConfigMap
apiVersion: v1
