metadata:
  name: gm-mutate-config
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: gm-webhook
        namespace: gm-operator
        path: /mutate-workload
    failurePolicy: Ignore
    name: mutate-workload.greymatter.io
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - gm-operator
            - spire
    rules:
      - apiGroups:
          - ""
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
          - deployments
          - statefulsets
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: gm-webhook
        namespace: gm-operator
        path: /mutate-mesh
    failurePolicy: Fail
    name: mutate-mesh.greymatter.io
    rules:
      - apiGroups:
          - greymatter.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - meshes
    sideEffects: None
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1