
{{- if .Values.create_operator_namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: gm-operator

{{- end }}
---
{{- if .Values.create_greymatter_namespace}}
metadata:
  labels:
    name: greymatter
  name: greymatter
kind: Namespace
apiVersion: v1
{{- end }}