metadata:
  name: gm-operator
  namespace: gm-operator
imagePullSecrets:
  - name: gm-docker-secret
  - name: quay-secret
kind: ServiceAccount
apiVersion: v1
---
metadata:
  name: gm-webhook-cert
  namespace: gm-operator
data:
  tls.crt: !!binary
  tls.key: !!binary
kind: Secret
apiVersion: v1
---