
metadata:
  name: gm-operator
  namespace: gm-operator
imagePullSecrets:
  - name: gm-docker-secret
  - name: quay-secret
kind: ServiceAccount
apiVersion: v1

---

metadata:
  name: vector-agent
  namespace: greymatter
  labels:
    app.kubernetes.io/instance: vector-agent
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/part-of: vector-agent
    app.kubernetes.io/version: 0.0.0
automountServiceAccountToken: true
kind: ServiceAccount
apiVersion: v1
---