metadata:
  name: gm-validate-config
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: gm-webhook
        namespace: gm-operator
        path: /validate-mesh
    failurePolicy: Fail
    name: validate-mesh.greymatter.io
    rules:
      - apiGroups:
          - greymatter.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - meshes
    sideEffects: None
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
