create_operator_namespace: false

operator:
  arguments:
    - -repo
    - git@github.com:greymatter-io/gitops-core.git
    - -sshPrivateKeyPath
    - /app/.ssh/ssh_private_key
    - -branch
    - no-auto-apply-image-pull-secret
    - -sshPrivateKeyPassword
    - password 